# Generated by Django 4.0.4 on 2022-05-03 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
